import "server-only";
import type { Prisma, PrismaClient } from "@/generated/prisma/client";
import { requirePermission } from "@/server/authorization/authorization";
import { writeAuditEvent } from "@/server/audit/audit-writer";
import type { AuthenticatedContext } from "@/server/auth/auth-types";
import { OrderError } from "./order-error";

type Db = PrismaClient | Prisma.TransactionClient;
const select = { id:true, orderNumber:true, status:true, customerId:true, customerSiteId:true, customerContactId:true, ownerMembershipId:true, orderedAt:true, dueDate:true, externalReference:true, memo:true, cancelledAt:true, cancellationReason:true, lockVersion:true, updatedAt:true, customer:{select:{code:true,name:true,active:true}}, customerSite:{select:{name:true,active:true}}, customerContact:{select:{name:true,active:true}}, ownerMembership:{select:{user:{select:{displayName:true}}}} } as const;
type Row = Prisma.SalesOrderGetPayload<{select:typeof select}>;
export type SalesOrderDto = ReturnType<typeof dto>;
function dto(row: Row) { return { id:row.id, orderNumber:row.orderNumber, status:row.status, customerId:row.customerId, customerSiteId:row.customerSiteId, customerContactId:row.customerContactId, ownerMembershipId:row.ownerMembershipId, orderedAt:row.orderedAt.toISOString().slice(0,10), dueDate:row.dueDate?.toISOString().slice(0,10) ?? null, externalReference:row.externalReference, memo:row.memo, cancelledAt:row.cancelledAt?.toISOString() ?? null, cancellationReason:row.cancellationReason, lockVersion:row.lockVersion, updatedAt:row.updatedAt.toISOString(), customer:row.customer, customerSite:row.customerSite, customerContact:row.customerContact, ownerName:row.ownerMembership?.user.displayName ?? null }; }
function snapshot(row: Row) { return { orderNumber:row.orderNumber,status:row.status,customerId:row.customerId,customerSiteId:row.customerSiteId,customerContactId:row.customerContactId,ownerMembershipId:row.ownerMembershipId,dueDate:row.dueDate?.toISOString().slice(0,10)??null,lockVersion:row.lockVersion }; }
function date(value: string | null | undefined) { return value ? new Date(`${value}T00:00:00.000Z`) : null; }
async function validateRefs(db: Db, org: string, input: {customerId:string; customerSiteId?:string|null; customerContactId?:string|null; ownerMembershipId?:string|null}) {
  const customer = await db.customer.findFirst({where:{id:input.customerId,organizationId:org,active:true,deletedAt:null},select:{id:true}}); if (!customer) throw new OrderError("INVALID_REQUEST","활성 거래처를 선택해 주세요.");
  if (input.customerSiteId && !(await db.customerSite.findFirst({where:{id:input.customerSiteId,organizationId:org,customerId:input.customerId,active:true,deletedAt:null},select:{id:true}}))) throw new OrderError("INVALID_REQUEST","선택한 고객 현장이 거래처와 일치하지 않거나 비활성입니다.");
  if (input.customerContactId && !(await db.customerContact.findFirst({where:{id:input.customerContactId,organizationId:org,customerId:input.customerId,active:true,deletedAt:null},select:{id:true}}))) throw new OrderError("INVALID_REQUEST","선택한 거래처 담당자가 거래처와 일치하지 않거나 비활성입니다.");
  if (input.ownerMembershipId && !(await db.organizationMembership.findFirst({where:{id:input.ownerMembershipId,organizationId:org,status:"ACTIVE"},select:{id:true}}))) throw new OrderError("INVALID_REQUEST","선택한 수주 담당자를 사용할 수 없습니다.");
}
async function getRow(db: Db, org:string,id:string) { const row=await db.salesOrder.findFirst({where:{id,organizationId:org},select}); if(!row) throw new OrderError("NOT_FOUND","수주를 찾을 수 없습니다."); return row; }
export async function listOrders(prisma:PrismaClient, context:AuthenticatedContext, input:{q?:string; status?:"DRAFT"|"CANCELLED"}) { requirePermission(context,"order.read"); const q=input.q?.trim(); const rows=await prisma.salesOrder.findMany({where:{organizationId:context.organizationId,...(input.status?{status:input.status}:{}),...(q?{OR:[{orderNumber:{contains:q,mode:"insensitive"}},{customer:{name:{contains:q,mode:"insensitive"}}}]}:{})},orderBy:[{updatedAt:"desc"},{id:"desc"}],take:50,select}); return rows.map(dto); }
export async function getOrder(prisma:PrismaClient,context:AuthenticatedContext,id:string) { requirePermission(context,"order.read"); return dto(await getRow(prisma,context.organizationId,id)); }
export async function createOrder(prisma:PrismaClient,context:AuthenticatedContext,input:{customerId:string;customerSiteId?:string|null;customerContactId?:string|null;ownerMembershipId?:string|null;dueDate?:string|null;externalReference?:string|null;memo?:string|null;requestId?:string}) { requirePermission(context,"order.edit"); return prisma.$transaction(async tx=>{await validateRefs(tx,context.organizationId,input); const year=new Date().getUTCFullYear(); const counter=await tx.salesOrderNumberCounter.upsert({where:{organizationId_sequenceYear:{organizationId:context.organizationId,sequenceYear:year}},create:{organizationId:context.organizationId,sequenceYear:year,nextValue:2},update:{nextValue:{increment:1}},select:{nextValue:true}}); const created=await tx.salesOrder.create({data:{organizationId:context.organizationId,sequenceYear:year,orderNumber:`SO-${year}-${String(counter.nextValue-1).padStart(6,"0")}`,customerId:input.customerId,customerSiteId:input.customerSiteId||null,customerContactId:input.customerContactId||null,ownerMembershipId:input.ownerMembershipId||context.membershipId,dueDate:date(input.dueDate),externalReference:input.externalReference?.trim()||null,memo:input.memo?.trim()||null},select}); await writeAuditEvent(tx,{organizationId:context.organizationId,actorUserId:context.userId,action:"order.created",entityId:created.id,requestId:input.requestId,after:snapshot(created)}); return dto(created); }); }
export async function updateOrder(prisma:PrismaClient,context:AuthenticatedContext,input:{id:string;expectedLockVersion:number;customerId:string;customerSiteId?:string|null;customerContactId?:string|null;ownerMembershipId?:string|null;dueDate?:string|null;externalReference?:string|null;memo?:string|null}) { requirePermission(context,"order.edit"); return prisma.$transaction(async tx=>{const old=await getRow(tx,context.organizationId,input.id); if(old.status!=="DRAFT") throw new OrderError("CONFLICT","취소된 수주는 수정할 수 없습니다."); if(old.lockVersion!==input.expectedLockVersion) throw new OrderError("CONFLICT","수주가 다른 화면에서 변경되었습니다. 최신 내용을 불러오세요."); await validateRefs(tx,context.organizationId,input); const row=await tx.salesOrder.update({where:{id:input.id},data:{customerId:input.customerId,customerSiteId:input.customerSiteId||null,customerContactId:input.customerContactId||null,ownerMembershipId:input.ownerMembershipId||null,dueDate:date(input.dueDate),externalReference:input.externalReference?.trim()||null,memo:input.memo?.trim()||null,lockVersion:{increment:1}},select}); return dto(row); }); }
export async function copyOrder(prisma:PrismaClient,context:AuthenticatedContext,id:string) { const original=await getOrder(prisma,context,id); if(original.status!=="DRAFT") throw new OrderError("CONFLICT","작성 중 수주만 복사할 수 있습니다."); return createOrder(prisma,context,{customerId:original.customerId,customerSiteId:original.customerSiteId,customerContactId:original.customerContactId,dueDate:original.dueDate,externalReference:original.externalReference,memo:original.memo}); }
export async function cancelOrder(prisma:PrismaClient,context:AuthenticatedContext,input:{id:string;expectedLockVersion:number;reason:string}) { requirePermission(context,"order.edit"); return prisma.$transaction(async tx=>{const old=await getRow(tx,context.organizationId,input.id); if(old.status!=="DRAFT") throw new OrderError("CONFLICT","이미 취소된 수주입니다."); if(old.lockVersion!==input.expectedLockVersion) throw new OrderError("CONFLICT","수주가 다른 화면에서 변경되었습니다. 최신 내용을 불러오세요."); const row=await tx.salesOrder.update({where:{id:input.id},data:{status:"CANCELLED",cancelledAt:new Date(),cancelledByMembershipId:context.membershipId,cancellationReason:input.reason.trim(),lockVersion:{increment:1}},select}); return dto(row); }); }
